# apiVersion: v1
# kind: Service
# metadata:
#   name: springboot-ingress-svc
# spec:
#   ports:
#     - name: springboot-ingress-svc
#       port: 80
#       targetPort: 8080
#       protocol: TCP
#   selector:
#     app: springboot-ingress-demo

---
apiVersion: v1
kind: Service
metadata:
  name: springboot-app-frontend
  namespace: myapp-demo
spec:
  type: LoadBalancer
  selector:
    app: springboot-app-demo
  ports:
    - name: http
      port: 80
      targetPort: 8080
