apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-argocd-demo
spec:
  selector:
    matchLabels:
      app: spring-argocd-demo
  replicas: 4
  template:
    metadata:
      labels:
        app: spring-argocd-demo
    spec:
      containers:
        - name: spring-argocd-demo
          image: asadiqbal6019/java-demo-app:main-33b5aad
          ports:
            - containerPort: 8080
