apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-argocd-demo
spec:
  selector:
    matchLabels:
      app: spring-argocd-demo
  replicas: 2
  template:
    metadata:
      labels:
        app: spring-argocd-demo
    spec:
      containers:
        - name: spring-argocd-demo
          # image: sumitgupta28/ocp-demo-app-kafka:latest
          image: asadiqbal6019/java-demo-app:main-c79696c
          ports:
            - containerPort: 8080
