apiVersion: v1
kind: Service
metadata:
  name: spring-service
  labels:
    app: spring-service
spec:
  type: NodePort
  selector:
    app: spring-argocd-demo
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30080
      name: http
