apiVersion: v1
kind: Service
metadata:
  name: springboot-app-frontend
  namespace: myapp-demo
spec:
   type: NodePort
  selector:
    app: spring-argocd-demo
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30000
      name: http
