apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app-demo
spec:
  selector:
    matchLabels:
      app: springboot-app-demo
      version: v1
  replicas: 2
  template:
    metadata:
      name: springboot-app-demo
      labels:
        app: springboot-app-demo
        version: v1
    spec:
      containers:
        - name: springboot-ingress-demo
          image: asadiqbal6019/java-demo-app:1.0
          ports:
            - containerPort: 8080
