apiVersion: v1
kind: Service
metadata:
  name: springboot-frontend-svc
  labels:
    app: springboot-frontend-svc
spec:
  type: LoadBalancer
  selector:
    app: springboot-app-demo
  ports:
    - name: http
      port: 80
      targetPort: 8080
# apiVersion: v1
# kind: Service
# metadata:
#   name: spring-service
#   labels:
#     app: spring-service
# spec:
#   type: NodePort
#   selector:
#     app: springboot-app-demo
#   ports:
#     - protocol: TCP
#       port: 8080
#       nodePort: 30081
#       name: http
