apiVersion: v1
kind: Service
metadata:
  name: springboot-frontend-svc
spec:
  type: LoadBalancer
  selector:
    app: springboot-app-demo
  ports:
    - name: http
      port: 80
      targetPort: 8080
